services:
  web:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    container_name: flynext-web
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - flynext-network

  nginx:
    image: nginx:alpine
    container_name: flynext-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
    networks:
      - flynext-network

  data-import:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    container_name: flynext-data-import
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      web:
        condition: service_started
    command: ["bash", "-c", "cd /app/my-app && node fetch.js && node fetch_hotel.js"]
    networks:
      - flynext-network

networks:
  flynext-network:
    driver: bridge